//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Albums")
export class AlbumsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
albumName: string;

@Column({nullable: true})
genre: string;

@Column({nullable: true})
rating: string;

@Column({nullable: true})
copiesSold: string;


}
