// Source code generated by AppGPT (www.appgpt.tech)

 //to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("authors")
export class authorsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
Name: string;

@Column("text",{nullable: true})
Biography: string;

@Column("date",{nullable: true})
DateOfBirth: Date;

@Column("text",{nullable: true})
Nationality: string;


}
