// Source code generated by AppGPT (www.appgpt.tech)

 //to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("customers")
export class customersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
Name: string;

@Column("text",{nullable: true})
Email: string;

@Column("text",{nullable: true})
PhoneNumber: string;

@Column("text",{nullable: true})
Address: string;

@Column("date",{nullable: true})
AccountCreationDate: Date;


}
