// Source code generated by AppGPT (www.appgpt.tech)

 //to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("loans")
export class loansEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
loanId: string;

@Column("integer",{nullable: true})
memberId: number;

@Column("date",{nullable: true})
issueDate: Date;

@Column("date",{nullable: true})
dueDate: Date;


}
