// Source code generated by AppGPT (www.appgpt.tech)

 //to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("loans")
export class loansEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
LoanID: string;

@Column("integer",{nullable: true})
Book: number;

@Column("integer",{nullable: true})
Member: number;

@Column("date",{nullable: true})
LoanDate: Date;

@Column("date",{nullable: true})
DueDate: Date;

@Column("date",{nullable: true})
ActualReturnDate: Date;


}
