// Source code generated by AppGPT (www.appgpt.tech)

 //to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("members")
export class membersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
name: string;

@Column("text",{nullable: true})
gender: string;

@Column("text",{nullable: true})
address: string;


}
