// Source code generated by AppGPT (www.appgpt.tech)

 //to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("orders")
export class ordersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("integer",{nullable: true})
OrderID: number;

@Column("integer",{nullable: true})
CustomerID: number;

@Column("date",{nullable: true})
OrderDate: Date;

@Column("real",{nullable: true})
TotalAmount: number;

@Column("text",{nullable: true})
Status: string;

@Column("text",{nullable: true})
ListOfProductsServicesOrdered: string;


}
