// Source code generated by AppGPT (www.appgpt.tech)

 //to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("teamMembers")
export class teamMembersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("integer",{nullable: true})
memberID: number;

@Column("text",{nullable: true})
name: string;

@Column("text",{nullable: true})
email: string;

@Column("text",{nullable: true})
role: string;

@Column("date",{nullable: true})
joinDate: Date;


}
