// Source code generated by AppGPT (www.appgpt.tech)

 //to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("tickets")
export class ticketsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("integer",{nullable: true})
TicketID: number;

@Column("integer",{nullable: true})
CustomerID: number;

@Column("text",{nullable: true})
IssueDescription: string;

@Column("text",{nullable: true})
Priority: string;

@Column("text",{nullable: true})
Status: string;

@Column("text",{nullable: true})
AssignedTo: string;

@Column("date",{nullable: true})
CreationDate: Date;

@Column("date",{nullable: true})
ResolutionDate: Date;


}
