//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Tracks")
export class TracksEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
trackName: string;

@Column({nullable: true})
duration: string;

@Column({nullable: true})
album: string;

@Column({nullable: true})
lyrics: string;

@Column({nullable: true})
rating: string;


}
