// Source code generated by AppGPT (www.appgpt.tech)

 import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput
} from "react-admin";
import { useRecordContext } from "react-admin";
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {

  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword =  '********';

  return (
      <span>{maskedPassword}</span>
  );
};
const ListActions = () => (
    <TopToolbar>
        <FilterButton />
        <CreateButton />
        <ExportButton />
        <SelectColumnsButton />
    </TopToolbar>
);
const ordersTitle = () => {
  const record = useRecordContext();
  return <span>orders {record ? `"${ record.OrderID }"` : ""}</span>;
};

export const ordersList = () => (
      <List actions={<ListActions  />} filters={ResourceFilters} >
        <DatagridConfigurable>
          <NumberField source="OrderID" />
<ReferenceField source="CustomerID" reference="customers"  />
<DateField source="OrderDate" />
<NumberField source="TotalAmount" />
<TextField source="Status" />
<EditButton />

        </DatagridConfigurable>
      </List>
      );

export const ordersEdit = () => (
                    <Edit title={<ordersTitle />}>
                      <SimpleForm>
                        <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
                          <Grid item xs={4}>
<NumberInput source="OrderID"   /></Grid>
<Grid item xs={4}>
<ReferenceInput source="CustomerID"  reference="customers"   /></Grid>
<Grid item xs={4}>
<DateInput source="OrderDate"   /></Grid>
<Grid item xs={4}>
<NumberInput source="TotalAmount"   /></Grid>
<Grid item xs={4}>
<TextInput source="Status"   /></Grid>
<Grid item xs={4}>
<TextInput source="ListOfProductsServicesOrdered"   /></Grid>
                        </Grid>
                      </SimpleForm>
                    </Edit>
                  );

export const ordersCreate = () => (
                                  <Create>
                                    <SimpleForm>
                                      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
                                        <Grid item xs={4}>
<NumberInput source="OrderID"   /></Grid>
<Grid item xs={4}>
<ReferenceInput source="CustomerID"  reference="customers"   /></Grid>
<Grid item xs={4}>
<DateInput source="OrderDate"   /></Grid>
<Grid item xs={4}>
<NumberInput source="TotalAmount"   /></Grid>
<Grid item xs={4}>
<TextInput source="Status"   /></Grid>
<Grid item xs={4}>
<TextInput source="ListOfProductsServicesOrdered"   /></Grid>
                                      </Grid>
                                    </SimpleForm>
                                  </Create>
                                );

const ResourceFilters = [
      <TextInput source="q" label="Search" alwaysOn />,
,
<ReferenceInput source="CustomerID" label="CustomerID" reference="customers"   alwaysOn/>,
,
,
,
,

    ];


