// Source code generated by AppGPT (www.appgpt.tech)

 import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput
} from "react-admin";
import { useRecordContext } from "react-admin";
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {

  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword =  '********';

  return (
      <span>{maskedPassword}</span>
  );
};
const ListActions = () => (
    <TopToolbar>
        <FilterButton />
        <CreateButton />
        <ExportButton />
        <SelectColumnsButton />
    </TopToolbar>
);
const ticketsTitle = () => {
  const record = useRecordContext();
  return <span>tickets {record ? `"${ record.TicketID }"` : ""}</span>;
};

export const ticketsList = () => (
      <List actions={<ListActions  />} filters={ResourceFilters} >
        <DatagridConfigurable>
          <NumberField source="TicketID" />
<ReferenceField source="CustomerID" reference="customers"  />

<TextField source="Priority" />
<TextField source="Status" />
<TextField source="AssignedTo" />
<DateField source="CreationDate" />
<DateField source="ResolutionDate" /><EditButton />

        </DatagridConfigurable>
      </List>
      );

export const ticketsEdit = () => (
                    <Edit title={<ticketsTitle />}>
                      <SimpleForm>
                        <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
                          <Grid item xs={4}>
<NumberInput source="TicketID"   /></Grid>
<Grid item xs={4}>
<ReferenceInput source="CustomerID"  reference="customers"   /></Grid>
<Grid item xs={4}>
<TextInput source="IssueDescription"   /></Grid>
<Grid item xs={4}>
<TextInput source="Priority"   /></Grid>
<Grid item xs={4}>
<TextInput source="Status"   /></Grid>
<Grid item xs={4}>
<TextInput source="AssignedTo"   /></Grid>
<Grid item xs={4}>
<DateInput source="CreationDate"   /></Grid>
<Grid item xs={4}>
<DateInput source="ResolutionDate"   /></Grid>
                        </Grid>
                      </SimpleForm>
                    </Edit>
                  );

export const ticketsCreate = () => (
                                  <Create>
                                    <SimpleForm>
                                      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
                                        <Grid item xs={4}>
<NumberInput source="TicketID"   /></Grid>
<Grid item xs={4}>
<ReferenceInput source="CustomerID"  reference="customers"   /></Grid>
<Grid item xs={4}>
<TextInput source="IssueDescription"   /></Grid>
<Grid item xs={4}>
<TextInput source="Priority"   /></Grid>
<Grid item xs={4}>
<TextInput source="Status"   /></Grid>
<Grid item xs={4}>
<TextInput source="AssignedTo"   /></Grid>
<Grid item xs={4}>
<DateInput source="CreationDate"   /></Grid>
<Grid item xs={4}>
<DateInput source="ResolutionDate"   /></Grid>
                                      </Grid>
                                    </SimpleForm>
                                  </Create>
                                );

const ResourceFilters = [
      <TextInput source="q" label="Search" alwaysOn />,
,
<ReferenceInput source="CustomerID" label="CustomerID" reference="customers"   alwaysOn/>,
,
,
,
,
,
,

    ];


