// Source code generated by AppGPT (www.appgpt.tech)

 import { Card, CardContent, CardHeader } from "@mui/material";
    export const Dashboard = () => (
      <Card>
      <CardHeader title="Annotator" />
      <CardContent> 
      It lets teams working with preparation of learning data for AI algorithms annotate the data appropriately
      <p>Built with{' '}
      <a
        href="https://www.appgpt.tech"
        target="_blank"
        rel="noopener noreferrer"
      >
        AppGPT
      </a></p>
      </CardContent>

      </Card>
    );