// Source code generated by AppGPT (www.appgpt.tech)

 // in i18nProvider.js
    import { mergeTranslations } from "ra-core";
    import polyglotI18nProvider from "ra-i18n-polyglot";
    import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

    const enResources = { resources: {"customers":{"name":"Customers","fields":{"Name":"Name","Email":"Email","PhoneNumber":"Phone Number","Address":"Address","AccountCreationDate":"Account Creation Date","id":"id"}},"orders":{"name":"Orders","fields":{"OrderID":"Order Id","CustomerID":"Customer Id","OrderDate":"Order Date","TotalAmount":"Total Amount","Status":"Status","ListOfProductsServicesOrdered":"List Of Products Services Ordered","id":"id"}},"tickets":{"name":"Tickets","fields":{"TicketID":"Ticket Id","CustomerID":"Customer Id","IssueDescription":"Issue Description","Priority":"Priority","Status":"Status","AssignedTo":"Assigned To","CreationDate":"Creation Date","ResolutionDate":"Resolution Date","id":"id"}}}};
const frResources = { resources: {"customers":{"name":"Customers (fr)","fields":{"Name":"Name (fr)","Email":"Email (fr)","PhoneNumber":"Phone Number (fr)","Address":"Address (fr)","AccountCreationDate":"Account Creation Date (fr)","id":"id"}},"orders":{"name":"Orders (fr)","fields":{"OrderID":"Order Id (fr)","CustomerID":"Customer Id (fr)","OrderDate":"Order Date (fr)","TotalAmount":"Total Amount (fr)","Status":"Status (fr)","ListOfProductsServicesOrdered":"List Of Products Services Ordered (fr)","id":"id"}},"tickets":{"name":"Tickets (fr)","fields":{"TicketID":"Ticket Id (fr)","CustomerID":"Customer Id (fr)","IssueDescription":"Issue Description (fr)","Priority":"Priority (fr)","Status":"Status (fr)","AssignedTo":"Assigned To (fr)","CreationDate":"Creation Date (fr)","ResolutionDate":"Resolution Date (fr)","id":"id"}}}};


    const en = mergeTranslations(enOriginal,enResources);
const fr = mergeTranslations(frOriginal,frResources);

    const translations = { en, fr};
    export const i18nProvider = polyglotI18nProvider(
      (locale) => translations[locale],
      "en", //default locale
      [{"locale":"en","name":"English"},{"locale":"fr","name":"Français"}]
    );
    