// Source code generated by AppGPT (www.appgpt.tech)

 // in i18nProvider.js
    import { mergeTranslations } from "ra-core";
    import polyglotI18nProvider from "ra-i18n-polyglot";
    import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

    const enResources = { resources: {"books":{"name":"Books","fields":{"title":"Title","author":"Author","isbn":"Isbn","genre":"Genre","id":"id"}},"authors":{"name":"Authors","fields":{"name":"Name","dateOfBirth":"Date Of Birth","id":"id"}},"members":{"name":"Members","fields":{"name":"Name","gender":"Gender","address":"Address","id":"id"}},"loans":{"name":"Loans","fields":{"loanId":"Loan Id","memberId":"Member Id","issueDate":"Issue Date","dueDate":"Due Date","id":"id"}}}};
const frResources = { resources: {"books":{"name":"Books (fr)","fields":{"title":"Title (fr)","author":"Author (fr)","isbn":"Isbn (fr)","genre":"Genre (fr)","id":"id"}},"authors":{"name":"Authors (fr)","fields":{"name":"Name (fr)","dateOfBirth":"Date Of Birth (fr)","id":"id"}},"members":{"name":"Members (fr)","fields":{"name":"Name (fr)","gender":"Gender (fr)","address":"Address (fr)","id":"id"}},"loans":{"name":"Loans (fr)","fields":{"loanId":"Loan Id (fr)","memberId":"Member Id (fr)","issueDate":"Issue Date (fr)","dueDate":"Due Date (fr)","id":"id"}}}};


    const en = mergeTranslations(enOriginal,enResources);
const fr = mergeTranslations(frOriginal,frResources);

    const translations = { en, fr};
    export const i18nProvider = polyglotI18nProvider(
      (locale) => translations[locale],
      "en", //default locale
      [{"locale":"en","name":"English"},{"locale":"fr","name":"Français"}]
    );
    