// Source code generated by AppGPT (www.appgpt.tech)

 // in i18nProvider.js
    import { mergeTranslations } from "ra-core";
    import polyglotI18nProvider from "ra-i18n-polyglot";
    import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

    const enResources = { resources: {"projects":{"name":"Projects","fields":{"projectName":"Project Name","description":"Description","startDate":"Start Date","endDate":"End Date","status":"Status","id":"id"}},"datasets":{"name":"Datasets","fields":{"datasetName":"Dataset Name","description":"Description","creationDate":"Creation Date","lastModifiedDate":"Last Modified Date","id":"id"}},"teamMembers":{"name":"Team Members","fields":{"memberID":"Member Id","name":"Name","email":"Email","role":"Role","joinDate":"Join Date","id":"id"}}}};
const frResources = { resources: {"projects":{"name":"Projects (fr)","fields":{"projectName":"Project Name (fr)","description":"Description (fr)","startDate":"Start Date (fr)","endDate":"End Date (fr)","status":"Status (fr)","id":"id"}},"datasets":{"name":"Datasets (fr)","fields":{"datasetName":"Dataset Name (fr)","description":"Description (fr)","creationDate":"Creation Date (fr)","lastModifiedDate":"Last Modified Date (fr)","id":"id"}},"teamMembers":{"name":"Team Members (fr)","fields":{"memberID":"Member Id (fr)","name":"Name (fr)","email":"Email (fr)","role":"Role (fr)","joinDate":"Join Date (fr)","id":"id"}}}};


    const en = mergeTranslations(enOriginal,enResources);
const fr = mergeTranslations(frOriginal,frResources);

    const translations = { en, fr};
    export const i18nProvider = polyglotI18nProvider(
      (locale) => translations[locale],
      "en", //default locale
      [{"locale":"en","name":"English"},{"locale":"fr","name":"Français"}]
    );
    